from selenium.webdriver.common.by import By

class AuthLocators:
    AUTH_PHONE = (By.ID, "username")
    AUTH_EMAIL = (By.ID, "username")
    AUTH_PASS = (By.ID, "password")
    AUTH_BTN = (By.ID, "kc-login")
    REG_LINK = (By.ID, "kc-register")
    PHONE_TAB_ELEMENT = (By.ID, "t-btn-tab-phone")
    MAIL_TAB_ELEMENT = (By.ID, "t-btn-tab-mail")
    LOGIN_TAB_ELEMENT = (By.ID, "t-btn-tab-login")
    LS_TAB_ELEMENT = (By.ID, "t-btn-tab-ls")
    LOGO_ELEMENT = (By.CSS_SELECTOR, "#page-left > div > div.what-is-container__logo-container > svg")
    INFO_ELEMENT = (By.CSS_SELECTOR, "#page-left > div > div.what-is")
    FOGOT_PASSW = (By.ID, "forgot_password")
    ERROR_AUTH = (By.ID, "form-error-message")
    KAPCHA_ELEMENT = (By.ID, "captcha")
    RESET_BTN = (By.ID, "reset")
    RESET_BACK = (By.ID, "reset-back")
    #registration
    REG_FIRSTNAME = (By.CSS_SELECTOR, "section#page-right > div > div > div > form > div > div > div > input")
    REG_LASTNAME = (By.CSS_SELECTOR, "section#page-right > div > div > div > form > div > div:nth-of-type(2) > div > input")
    REG_ADDRESS = (By.ID, "address")
    REG_REGION = (By.CSS_SELECTOR, "section#page-right > div > div > div > form > div:nth-of-type(2) > div > div > input")
    REG_PASSW_CONFIRM = (By.ID, "password-confirm")
    REG_LINK_CONFIDENTAL = (By.CSS_SELECTOR, "section#page-right > div > div > div > form > div:nth-of-type(5) > a")
    REG_LOGO = (By.CSS_SELECTOR, "header#app-header > div > div > svg")
    REG_BTN = (By.CSS_SELECTOR, "section#page-right > div > div > div > form > button")
    CONFIRM_EMAIL = (By.CSS_SELECTOR, "section#page-right > div > div > h1")
    REG_ERROR_NAME = (By.CSS_SELECTOR, "section#page-right > div > div > div > form > div > div > span")
